export const dashboardTypes = {
  GET_PRODUCTS: 'GET_PRODUCTS',
  SEARCH_PRODUCTS: 'SEARCH_PRODUCTS',
  CATEGORY_VIEW: 'CATEGORY_VIEW',
  AUTHOR_VIEW: 'AUTHOR_VIEW',
  POST_LOGIN: 'POST_LOGIN',
  ADD_TO_CART: 'ADD_TO_CART',
}
